import { Employee } from "./types";

export let data: Employee[] | any = [
  {
    id: "1",
    firstName: "Ali",
    lastName: "Benhaddou",
    workTime: "9:00 AM - 5:00 PM",
    status: "success",
    email: "ali.benhaddou@gmail.com",
  },
  {
    id: "2",
    firstName: "Khadija",
    lastName: "El Fassi",
    workTime: "10:00 AM - 6:00 PM",
    status: "processing",
    email: "khadija.elfassi@hotmail.com",
  },
  {
    id: "3",
    firstName: "Mohamed",
    lastName: "Boukili",
    workTime: "11:00 AM - 7:00 PM",
    status: "failed",
    email: "mohamed.boukili@yahoo.com",
  },
  {
    id: "4",
    firstName: "Fatima",
    lastName: "Zahra",
    workTime: "8:00 AM - 4:00 PM",
    status: "pending",
    email: "fatima.zahra@example.com",
  },
  {
    id: "5",
    firstName: "Hassan",
    lastName: "El Idrissi",
    workTime: "9:30 AM - 5:30 PM",
    status: "success",
    email: "hassan.elidrissi@gmail.com",
  },
  {
    id: "6",
    firstName: "Amina",
    lastName: "Tazi",
    workTime: "8:30 AM - 4:30 PM",
    status: "success",
    email: "amina.tazi@gmail.com",
  },
  {
    id: "7",
    firstName: "Youssef",
    lastName: "Benzakour",
    workTime: "9:00 AM - 5:00 PM",
    status: "pending",
    email: "youssef.benzakour@example.com",
  },
  {
    id: "8",
    firstName: "Zineb",
    lastName: "Rachidi",
    workTime: "10:00 AM - 6:00 PM",
    status: "success",
    email: "zineb.rachidi@hotmail.com",
  },
  {
    id: "9",
    firstName: "Omar",
    lastName: "El Mansouri",
    workTime: "11:00 AM - 7:00 PM",
    status: "processing",
    email: "omar.elmansouri@yahoo.com",
  },
  {
    id: "10",
    firstName: "Salma",
    lastName: "Belkacem",
    workTime: "8:00 AM - 4:00 PM",
    status: "failed",
    email: "salma.belkacem@example.com",
  },
  {
    id: "11",
    firstName: "Imane",
    lastName: "El Khoury",
    workTime: "9:30 AM - 5:30 PM",
    status: "success",
    email: "imane.elkhoury@gmail.com",
  },
  {
    id: "12",
    firstName: "Rachid",
    lastName: "Mouhajir",
    workTime: "8:30 AM - 4:30 PM",
    status: "pending",
    email: "rachid.mouhajir@example.com",
  },
  {
    id: "13",
    firstName: "Siham",
    lastName: "Abidi",
    workTime: "9:00 AM - 5:00 PM",
    status: "success",
    email: "siham.abidi@gmail.com",
  },
  {
    id: "14",
    firstName: "Abdellah",
    lastName: "Kabbaj",
    workTime: "10:00 AM - 6:00 PM",
    status: "processing",
    email: "abdellah.kabbaj@hotmail.com",
  },
  {
    id: "15",
    firstName: "Meryem",
    lastName: "El Majidi",
    workTime: "11:00 AM - 7:00 PM",
    status: "success",
    email: "meryem.elmajidi@yahoo.com",
  },
  {
    id: "16",
    firstName: "Nabil",
    lastName: "Cherkaoui",
    workTime: "8:00 AM - 4:00 PM",
    status: "failed",
    email: "nabil.cherkaoui@example.com",
  },
  {
    id: "17",
    firstName: "Hind",
    lastName: "El Ouafi",
    workTime: "9:30 AM - 5:30 PM",
    status: "success",
    email: "hind.elouafi@gmail.com",
  },
  {
    id: "18",
    firstName: "Karim",
    lastName: "Bennani",
    workTime: "8:30 AM - 4:30 PM",
    status: "pending",
    email: "karim.bennani@example.com",
  },
  {
    id: "19",
    firstName: "Leila",
    lastName: "Ouazzani",
    workTime: "9:00 AM - 5:00 PM",
    status: "success",
    email: "leila.ouazzani@gmail.com",
  },
  {
    id: "20",
    firstName: "Anass",
    lastName: "Jabri",
    workTime: "10:00 AM - 6:00 PM",
    status: "processing",
    email: "anass.jabri@hotmail.com",
  },
  {
    id: "21",
    firstName: "Sara",
    lastName: "Alaoui",
    workTime: "11:00 AM - 7:00 PM",
    status: "success",
    email: "sara.alaoui@yahoo.com",
  },
  {
    id: "22",
    firstName: "Ismail",
    lastName: "Naji",
    workTime: "8:00 AM - 4:00 PM",
    status: "failed",
    email: "ismail.naji@example.com",
  },
  {
    id: "23",
    firstName: "Nouha",
    lastName: "El Alami",
    workTime: "9:30 AM - 5:30 PM",
    status: "success",
    email: "nouha.elalami@gmail.com",
  },
  {
    id: "24",
    firstName: "Walid",
    lastName: "Amrani",
    workTime: "8:30 AM - 4:30 PM",
    status: "pending",
    email: "walid.amrani@example.com",
  },
  {
    id: "25",
    firstName: "Hayat",
    lastName: "Chraibi",
    workTime: "9:00 AM - 5:00 PM",
    status: "success",
    email: "hayat.chraibi@gmail.com",
  },
];
